### PR TITLE
Reorg

### PR DESCRIPTION
**Pull request by pfdamasceno**
- [x] add Google's turbo colors
- [ ] add explanation for Laplacians
- [x] fix bug when column name doesn't exist
- [x] add function to convert df to brain_painter naming scheme

### CODE REVIEW

**Comment by axiezai** [comment]
Need to confirm origin of `laplacian.mat`

**Comment by axiezai** [comment]
@pedro-maia which connectivity matrix did you create `laplacian.mat` from?

**Comment by PDMaia** [comment]
> @pedro-maia which connectivity matrix did you create `laplacian.mat` from?

The **laplacians.mat** was created using the **L_for_Pablo.m** on C matrix provided from **meanACS69.mat**. Please find the mentioned files in the zip archive
[requested_files.zip](https://github.com/Raj-Lab-UCSF/cortography/files/4062500/requested_files.zip)

**Comment by axiezai** [comment]
I think I've seen `meanACS69.mat` somewhere before, I just don't know which atlas it's based off of and for which subject? Is this the mean connectivity matrix from HCP data in DK-86 region atlas?

**Pull request merged**
